backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

slug: { encoding: ascii, clean_accents: true }

collections:
  - name: pages
    label: Cấu hình
    files:
      - name: home
        label: Trang chủ
        file: static/pages/home.yml
        fields:
          - { name: title, label: Tiêu đề }
          - { name: subTitle, label: Tiêu đề phụ }
          - { name: hotelImage, label: Hình danh mục khách sạn, widget: image }
          - { name: golfImage, label: Hình danh mục sân golf, widget: image }
          - { name: restaurantImage, label: Hình danh mục nhà hàng, widget: image }
  - name: services
    label: Dịch vụ
    folder: static/services
    create: true
    fields:
      - { name: title, label: Tên dịch vụ, widget: string }
      - name: type
        label: Loại hình
        widget: select
        options:
          - { label: Khách sạn, value: hotel }
          - { label: Sân golf, value: golf }
          - { label: Nhà hàng, value: restaurant }
      - { name: address, label: Địa chỉ, widget: string }
      - name: images
        label: Hình ảnh
        widget: list
        field: { label: Hình ảnh, name: image, widget: image }
      - { name: body, label: Mô tả, widget: markdown }
  - name: articles
    label: Bài viết
    folder: static/articles
    create: true
    fields:
      - { name: title, label: Tiêu đề, widget: string }
      - { name: createdAt, label: Ngày đăng, widget: date, format: DD/MM/YYYY }
      - { name: thumbnail, label: Hình ảnh, widget: image }
      - { name: body, label: Nội dung, widget: markdown }
      - { name: tags, label: Thẻ bài viết, widget: list }
