backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

slug: { encoding: ascii, clean_accents: true }

collections:
  - name: pages
    label: Cấu hình
    editor:
      preview: false
    files:
      - name: home
        label: Trang chủ
        file: static/pages/home.yml
        fields:
          - { name: title, label: Tiêu đề }
          - { name: subTitle, label: Tiêu đề phụ }
          - { name: hotelImage, label: Hình danh mục khách sạn, widget: image }
          - { name: golfImage, label: Hình danh mục sân golf, widget: image }
          - { name: restaurantImage, label: Hình danh mục nhà hàng, widget: image }
  - name: services
    label: Dịch vụ
    folder: static/services
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Tên dịch vụ, widget: string }
      - name: language
        label: Ngôn ngữ
        widget: select
        default: vietnamese
        options:
          - { label: Tiếng Việt, value: vietnamese }
          - { label: Tiếng Anh, value: english }
          - { label: Tiếng Hàn, value: korean }
          - { label: Tiếng Nhật, value: japanese }
      - name: type
        label: Loại hình
        widget: select
        options:
          - { label: Khách sạn, value: hotel }
          - { label: Sân golf, value: golf }
          - { label: Nhà hàng, value: restaurant }
      - { name: address, label: Địa chỉ, widget: string }
      - name: images
        label: Hình ảnh
        widget: list
        field: { label: Hình ảnh, name: image, widget: image }
      - { name: body, label: Mô tả, widget: markdown }
      - { name: price, label: Giá, widget: string }
      - { name: featured, label: Hiện lên trang chủ, widget: boolean, default: true }
      - { name: createdAt, label: Ngày đăng, widget: date, format: DD/MM/YYYY }
      - name: utilities
        label: Tiện nghi
        widget: list
        required: false
        fields:
          - name: icon
            label: Icon
            widget: select
            options:
              - { label: Wifi, value: wifi }
              - { label: Nước nóng, value: hot-water }
              - { label: Giặt ủi, value: laundry }
              - { label: Điều hoà, value: air-conditioner }
          - { name: title, label: Tên tiện ích, widget: string }
      - { name: sokhach, label: Số khách (nếu có), widget: number, required: false, hint: 'Số khách tối đa của dịch vụ phòng khách sạn' }
      - { name: sogiuong, label: Số giường (nếu có), widget: number, required: false , hint: 'Số giường của dịch vụ phòng khách sạn'}
      - { name: sophongtam, label: Số phòng tắm (nếu có), widget: number, required: false , hint: 'Số phòng tắm của dịch vụ phòng khách sạn'}
      - { name: solo, label: Số lỗ Golf (nếu có), widget: number, required: false , hint: 'Số lỗ Golf của dịch vụ đặt sân Golf'}
      - { name: dientich, label: Diện tích sân (nếu có), widget: string, required: false , hint: 'Diện tích sân của dịch vụ đặt sân Golf'}
  - name: articles
    label: Bài viết
    folder: static/articles
    create: true
    fields:
      - { name: title, label: Tiêu đề, widget: string }
      - { name: createdAt, label: Ngày đăng, widget: date, format: DD/MM/YYYY }
      - { name: thumbnail, label: Hình ảnh, widget: image }
      - { name: body, label: Nội dung, widget: markdown }
      - { name: tags, label: Thẻ bài viết, widget: list }
