backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

slug: { encoding: ascii, clean_accents: true }

collections:
  - name: pages
    label: Cấu hình
    editor:
      preview: false
    files:
      - name: home
        label: Trang chủ
        file: static/pages/home.yml
        fields:
          - { name: hotelImage, label: Hình danh mục khách sạn, widget: image }
          - { name: golfImage, label: Hình danh mục sân golf, widget: image }
          - { name: restaurantImage, label: Hình danh mục nhà hàng, widget: image }
      - name: contact
        label: Thông tin liên hệ
        file: static/pages/contact.yml
        fields:
          - { name: companyName, label: Tên công ty }
          - { name: address, label: Địa chỉ công ty }
          - { name: phone, label: Số điện thoại }
          - { name: email, label: Email liên hệ }
          - { name: managerEmail, label: Email nhận đặt phòng }
          - { name: facebookUrl, label: Địa chỉ Facebook, required: false }
          - { name: contactBackground, label: Hình trang liên hệ, widget: image }
  - name: services
    label: Dịch vụ
    folder: static/services
    create: true
    editor:
      preview: false
    fields:
      - name: type
        label: Loại hình
        widget: select
        default: hotel
        options:
          - { label: Khách sạn, value: hotel }
          - { label: Sân golf, value: golf }
          - { label: Nhà hàng, value: restaurant }
      - { name: title, label: Tên dịch vụ (Tiếng Việt), widget: string }
      - { name: titleEng, label: Tên dịch vụ (Tiếng Anh), widget: string, required: false }
      - { name: titleKor, label: Tên dịch vụ (Tiếng Hàn), widget: string, required: false }
      - { name: address, label: Địa chỉ (Tiếng Việt), widget: string }
      - { name: addressEng, label: Địa chỉ (Tiếng Anh), widget: string, required: false }
      - { name: addressKor, label: Địa chỉ (Tiếng Hàn), widget: string, required: false }
      - name: images
        label: Hình ảnh
        widget: list
        field: { label: Hình ảnh, name: image, widget: image }
      - { name: body, label: Mô tả (Tiếng Việt), widget: markdown }
      - { name: bodyEng, label: Mô tả (Tiếng Anh), widget: markdown, required: false }
      - { name: bodyKor, label: Mô tả (Tiếng Hàn), widget: markdown, required: false }
      - { name: price, label: Giá (Tiếng Việt), widget: string }
      - { name: priceEng, label: Giá (Tiếng Anh), widget: string, required: false }
      - { name: priceKor, label: Giá (Tiếng Hàn), widget: string, required: false }
      - { name: featured, label: Hiện lên trang chủ, widget: boolean, default: true }
      - { name: createdAt, label: Ngày đăng, widget: date, format: DD/MM/YYYY }
      - name: utilities
        label: Tiện nghi
        widget: list
        required: false
        fields:
          - name: icon
            label: Icon
            widget: select
            options:
              - { label: Wifi, value: wifi }
              - { label: Nước nóng, value: hot-water }
              - { label: Giặt ủi, value: laundry }
              - { label: Điều hoà, value: air-conditioner }
          - { name: title, label: Tên tiện ích (Tiếng Việt), widget: string }
          - { name: titleEng, label: Tên tiện ích (Tiếng Anh), widget: string, required: false  }
          - { name: titleKor, label: Tên tiện ích (Tiếng Hàn), widget: string, required: false  }
      - { name: sokhach, label: Số khách (nếu có), widget: number, required: false, hint: 'Số khách tối đa của dịch vụ phòng khách sạn' }
      - { name: sogiuong, label: Số giường (nếu có), widget: number, required: false , hint: 'Số giường của dịch vụ phòng khách sạn'}
      - { name: sophongtam, label: Số phòng tắm (nếu có), widget: number, required: false , hint: 'Số phòng tắm của dịch vụ phòng khách sạn'}
      - { name: solo, label: Số lỗ Golf (nếu có), widget: number, required: false , hint: 'Số lỗ Golf của dịch vụ đặt sân Golf'}
      - { name: dientich, label: Diện tích sân (nếu có), widget: string, required: false , hint: 'Diện tích sân của dịch vụ đặt sân Golf'}
  - name: articles
    label: Bài viết
    folder: static/articles
    create: true
    fields:
      - { name: title, label: Tiêu đề, widget: string }
      - { name: createdAt, label: Ngày đăng, widget: date, format: DD/MM/YYYY }
      - { name: thumbnail, label: Hình ảnh, widget: image }
      - { name: body, label: Nội dung, widget: markdown }
      - { name: tags, label: Thẻ bài viết, widget: list }
